language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
script: bundle exec rake spec_travis
gemfile: .travis.gemfile
before_script:
  - mysql -e 'create database sequel_test;'
  - psql -c 'create database sequel_test;' -U postgres
